### PR TITLE
Add 1/6 grid "micro" panel size

### PR DESCRIPTION
**Pull request by netcarver**

### CODE REVIEW

**Comment by netcarver** [comment]
Reopened as I can't seem to apply this against the develop branch. Anyway, hope you get the gist.

**Comment by daun** [comment]
@netcarver  Do you find you need the `micro` size in addition to the `mini` size or instead of it?

**Comment by netcarver** [comment]
@daun, Hi Philipp, I use the new micro panel size _in addition_ to the mini size. And my apologies for the mess prepping this PR.

**Comment by daun** [comment]
No worries. I'm currently on vacation, I'll look into this next week or the week after.

**Comment by daun** [comment]
Released in 1.5.0. Thanks for contributing :)

**Pull request merged**
